# ######## Jekyll Site Settings ##########
remote_theme: jekyll-theme-profile
title: Sarvsav Profile
description: My personal blog
image: /media/appbar-preview.png
repository: sarvsav/sarvsav.github.io
base_url: ""
url: "https://sarvsav.github.io"

collections:
  docs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      image: /assets/img/default.png # The default image used for social and posts.
      toc: true
  - scope:
      path: "" # an empty string here means all files in the project
      type: "docs"
    values:
      layout: "docs"
      image: /assets/img/default.png # The default image used for social and posts.
      permalink: /docs/:path:output_ext
      toc: true

# ########### Theme settings ###############
# The style of the website
style: topbar # One of "stacked", "sidebar", "topbar", "appbar"
# The user/project avatar.  If not set the avatar of the project owner will be used.
user_image: /media/user-image.jpg
# The themes to use for dark and light
dark_theme: dark_dimmed
light_theme: light
# # Optional custom background image and overlay
# background:
#   image: /media/background-img.jpg
#   overlay: rgba(0, 0, 0, 0.7)
#   light:
#     overlay: rgba(255, 255, 255, 0.5)
#   dark:
#     overlay: rgba(0, 0, 0, 0.5)

# # Optional custom header colors
# header:
#   color: "#4051b5"
#   text: "rgba(255,255,255,0.7)"
#   accent: "#ffffff"

repo_info: true # Show the information for the source of this project
user_metadata: true # Show the metadata associated with the user
profile_link: true # Show a link to the github profile for the user

##########################
# # Social media settings
icon_color: "#959da5" # The color of the social media icons on the site
social_media: # Your social media accounts
  # behance: your_username
  # dribbble: your_username
  # docker: your_username
  # facebook: your_username
  github: sarvsav
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mail: email@address
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # threads: your_username
  # tiktok: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  vscode: sarvsav
  # youtube: your_username
  x: sarvsav

####################
# Navigation links
nav:
  - name: Topbar
    url: /topbar.html
  - name: Appbar
    url: /appbar.html
  - name: Sidebar
    url: /sidebar.html
  - name: Stacked
    url: /stacked.html
  - name: Documentation
    url: /docs

####################
# List of links for link cards
links:
  - name: Example page with topbar
    url: /page/topbar
    thumbnail: /media/topbar-icon.png
  - name: Example page with appbar
    url: /page/appbar
    thumbnail: /media/appbar-icon.png
  - name: Example page with sidebar
    url: /page/sidebar
    thumbnail: /media/sidebar-icon.png
  - name: Example page with header stacked
    url: /page/stacked
    thumbnail: /media/stacked-icon.png
  - name: Example custom background
    url: /background
    thumbnail: /media/icon-bg.png
  - name: Example Linktree page
    url: /linktree
    thumbnail: /media/links.png
  - name: Example Profile page
    url: /profile
    thumbnail: /media/user-image.jpg
  - name: Example Reposotiries page
    url: /repositories
    thumbnail: /media/repositories.png

###################
# Repositories to show on home page
repositories:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 24
  exclude:
    archived: true
    forks: true
    repositories:
      # - list of respositories to exclude

########################
# Post timeline
posts_limit: 3 # The number of posts to show in home (also can be defined in page)

# ########### Plugin settings ###############
plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji
####################
# jekyll-paginate settings
paginate: 6 # The number of posts to show per page of pagination of blog posts
paginate_path: "/blog/page:num"
###################
# jekyll-tagging settings
# Include `gem jekyll-tagging` in your gemfile
tag_page_layout: tags
tag_page_dir: tags
# related
related_by: "tags or categories"

####################
# jekyll-category-pages settings
category_path: category
category_layout: category_layout.html

######################
# jekyll-relative-links settings
relative_links:
  enabled: true
  collections: true
